PATCH /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/awards/14f4c1774be847098f247565c4871574?acc_token=a94a2b6627aa46f3bbb83ff885e3beae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-11-30T16:56:27.695166+02:00", 
      "endDate": "2017-11-30T16:56:27.920508+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "afaa508128da4829b9202fe300965bf4", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-11-30T16:56:27.927179+02:00", 
    "id": "14f4c1774be847098f247565c4871574"
  }
}

