PATCH /api/2.3/auctions/e697023cacc24697a8d03c234753bbd0/awards/ad468ef737c34ac2b2ae65a80b2ca8e1?acc_token=9575071a6c92489782d67ec29cbcc30f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/e697023cacc24697a8d03c234753bbd0/awards/9d25afbaccdb43b7b0de63e172fa9437

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/eebd2b6d4c7b4e1497dcbf6b1791585a?KeyID=18f3f87d&Signature=NH89p3ErX15HXsSQldd2va7q1Qz6coZnuMgw5tpE7dWXLoXh5M5oEAGNTMRXS%252B9uzvEEMPI1Tv%2FZTMg6YhRBDQ%253D%253D", 
        "title": "Disqualified_reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:31.285744+03:00", 
        "dateModified": "2017-03-29T15:47:31.285770+03:00", 
        "id": "76a5b88495ea4ee6a777c5ce9d9d2d37"
      }
    ], 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "complaintPeriod": {
      "startDate": "2017-03-29T15:47:31.134325+03:00", 
      "endDate": "2017-03-29T15:47:31.417212+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "title": "Disqualified", 
    "bid_id": "9dba89da1a4b4a179940243cda57bb7a", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-03-29T15:47:31.432934+03:00", 
    "id": "ad468ef737c34ac2b2ae65a80b2ca8e1"
  }
}

