PATCH /api/2.3/auctions/73e1598288054eb98e8153ee9e69bb28/bids/c7a52fb296b143cc87728f74b2585fca?acc_token=b6c5e3c4087848a08703ae24889033a7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

