PATCH /api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/bids/cbaa01edfc704658b0f98486ba015ad0?acc_token=5c483486da504fc992e559535052e741 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

