PATCH /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/cancellations/3fd26d96a4454abf9a875bef110dba4e?acc_token=ccf4d45ff9524ec9ae87f38c43d7b0a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/02dd9977d20e4b409d307bc67ee6ca36?KeyID=8473a74a&Signature=5WtHn%252BXf4U2eKnBY5mwdZNifHaf%2FMoApsRroJSOzQBI%252BdJ5ZwCkP%252BTZmjkZ%2FDOh1M4U5JY7u1MJE8%252Bp7YQOSBw%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:29.945693+02:00", 
        "dateModified": "2017-11-30T16:56:29.945720+02:00", 
        "id": "6aebbc98305a4847830bdc40863a4d6b"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1981cae19a6d4577bf343cf0b7d813f5?KeyID=8473a74a&Signature=6PDYxf6GgOgkJuoH%2FR4qtBFHx%2FEcXKpV9NJ0lWVPu7IBKLdQ8%252ByiK5kIQk5YZ9aebaDik0e4JNDdJihcZVA%252BBg%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:29.945693+02:00", 
        "dateModified": "2017-11-30T16:56:30.284752+02:00", 
        "id": "6aebbc98305a4847830bdc40863a4d6b"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2017-11-30T16:56:30.483484+02:00", 
    "cancellationOf": "tender", 
    "id": "3fd26d96a4454abf9a875bef110dba4e"
  }
}

