PATCH /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/questions/c6c6259846504cfbb4e38d9c5d543958?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2017-03-29T15:47:34.865633+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "c6c6259846504cfbb4e38d9c5d543958", 
    "questionOf": "tender"
  }
}

