GET /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c683de25eb294b5fa8cc8294ec9fe908?KeyID=8f2f71ed&Signature=b1At6NDAC3JTU6fDd9uTHG1sI%2FzioJcoVHbxqTzZAELtHr3FwOjQ9yMpVBRf%2FFrizC84qhF2xqlfr51ifFqoBg%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:34.401607+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-03-29T15:47:34.401638+03:00", 
      "id": "2a0f652e19154a218c608f42a5c448e0"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a70797d6dbde47c897ae6a0dfe2af58e?KeyID=8f2f71ed&Signature=PSvGpJaKdUzNhQ5doYcyhvffRxRvLNo2w3YI5U9fSNzR5%2FOp2TZCDDj6Ebre6Wfc7zgLutisTUqCzBy7X4fBBg%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:34.472264+03:00", 
      "dateModified": "2017-03-29T15:47:34.531556+03:00", 
      "id": "18fb51d188ce405e875dfb37f1baf161"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7775106db07c466c9750e75e3a1b1d6b?KeyID=8f2f71ed&Signature=ILUThMRo0qZCi8tZWpKJU3823B3hGbztKBm7Xm25aJXdqBbYELIZDig2uPsixRPRueqmQBR7imEfx3lJrAv1CQ%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:34.591738+03:00", 
      "documentType": "illustration", 
      "dateModified": "2017-03-29T15:47:34.591779+03:00", 
      "id": "8c81536a6660418483282224f74adfec"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4729e391cb144b07991bac85f9c818c5?KeyID=8f2f71ed&Signature=jFB8Hk2RJDmeK6F%2Flwn7VOnF4YACkiKim38m19aiGbnpwg0HB%2FOHxh0jBicpQblc7FuPXhMJpU%2FEDgElJoNBDw%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:34.656709+03:00", 
      "documentType": "illustration", 
      "dateModified": "2017-03-29T15:47:34.656745+03:00", 
      "id": "6e61fb44da8145ed89b3762be3ef21f6"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7085d82dbfc4481fadf1ea3398627992?KeyID=8f2f71ed&Signature=90AdYhugdyIJ8Na8%2FJBokHs%252BOUpjxiUfBhXvINxrzqd0rvQOwHap64cd1qvN4uqEUZipHq%2FHxfvi%252BHWHGRwqDA%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:34.713380+03:00", 
      "documentType": "illustration", 
      "dateModified": "2017-03-29T15:47:34.713406+03:00", 
      "id": "72ae2b129ab4497ea20f48fea7d518be"
    }
  ]
}

