POST /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7/documents?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 348
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4a36a987d33846ce873195d6b53fbcdc?KeyID=8f2f71ed&Signature=wAD1TVl5Jq2Kx35yWFoc5FceK1WIs895vyy6OveYwELP9M0FSSvrwbJFkFEG%2FnaAgzUWKVb6S6JKGGNO6dVZAQ%3D%3D", 
    "title": "contract_second_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7/documents/0c9d642e2a29402591bd60c0d9de16f3

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4a36a987d33846ce873195d6b53fbcdc?KeyID=8f2f71ed&Signature=TJHSDvK%252B25lwWqrTpCHw%2FxFajvBCLFy424jp%252BNekwCwclJp7a7xDVthyjFFK0GWry3%2F82FeruAcw0qBP67nKDQ%253D%253D", 
    "title": "contract_second_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:36.562256+03:00", 
    "dateModified": "2017-03-29T15:47:36.562283+03:00", 
    "id": "0c9d642e2a29402591bd60c0d9de16f3"
  }
}

