GET /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/contracts/ada81c2080f143a387863faae3db1f81/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5bd3f7a02ff44727b232621207f1b851?KeyID=8473a74a&Signature=JQHt0PL4w47AD3VLzHc10HkPeKF1%252BHLSabNSU66N7xOOgzeZ5ABgvszpMW%252Bf1dAvGCTqIVBaD2EYUV1iUuYZAQ%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2017-11-30T16:56:28.913379+02:00", 
      "dateModified": "2017-11-30T16:56:28.913410+02:00", 
      "id": "1702fe06543e4c10b6f0bcb0aa694e8c"
    }
  ]
}

