POST /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7/documents?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 351
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/faeb5c861bc44c298b554f48d99b2241?KeyID=8f2f71ed&Signature=HFtmu79CrUkyaE7jRPTH6OlUIwy4xhnsCQyRLAtj17z5UGUVdsgjer1EJ5%2BJKj%2FlctcXTf%2BtYBHiOXUbTgR9Ag%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7/documents/8be61adfb48f4fdb8f904d31f3752503

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/faeb5c861bc44c298b554f48d99b2241?KeyID=8f2f71ed&Signature=txDsfHH5fx69yaYLizGYkvhwT2Am2z14Zs8EsWtmIQbYObK43l3wljIBr5b3acG%2F%2FqSHrpRgCn%252B2xPXj03qpDA%253D%253D", 
    "title": "contract_first_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:36.395141+03:00", 
    "dateModified": "2017-03-29T15:47:36.395171+03:00", 
    "id": "8be61adfb48f4fdb8f904d31f3752503"
  }
}

