PATCH /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2017-03-29T15:47:36.691689+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/faeb5c861bc44c298b554f48d99b2241?KeyID=8f2f71ed&Signature=txDsfHH5fx69yaYLizGYkvhwT2Am2z14Zs8EsWtmIQbYObK43l3wljIBr5b3acG%2F%2FqSHrpRgCn%252B2xPXj03qpDA%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:36.395141+03:00", 
        "dateModified": "2017-03-29T15:47:36.395171+03:00", 
        "id": "8be61adfb48f4fdb8f904d31f3752503"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4a36a987d33846ce873195d6b53fbcdc?KeyID=8f2f71ed&Signature=TJHSDvK%252B25lwWqrTpCHw%2FxFajvBCLFy424jp%252BNekwCwclJp7a7xDVthyjFFK0GWry3%2F82FeruAcw0qBP67nKDQ%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:36.562256+03:00", 
        "dateModified": "2017-03-29T15:47:36.562283+03:00", 
        "id": "0c9d642e2a29402591bd60c0d9de16f3"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "d3a6b745e6ec4a3fabba32445167d78c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-03-29T15:47:26.507025+03:00", 
      "endDate": "2018-03-29T15:47:26.507025+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-03-29T15:47:36.691689+03:00", 
    "date": "2017-03-29T15:47:36.775524+03:00", 
    "awardID": "a3d2d0c829fb45c9b73a75e7d1978991", 
    "id": "46acb818c454494fb3ea95be84b530f7", 
    "contractID": "UA-PS-2017-03-29-000001-1"
  }
}

