GET /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/contracts/46acb818c454494fb3ea95be84b530f7/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/faeb5c861bc44c298b554f48d99b2241?KeyID=8f2f71ed&Signature=txDsfHH5fx69yaYLizGYkvhwT2Am2z14Zs8EsWtmIQbYObK43l3wljIBr5b3acG%2F%2FqSHrpRgCn%252B2xPXj03qpDA%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:36.395141+03:00", 
      "dateModified": "2017-03-29T15:47:36.395171+03:00", 
      "id": "8be61adfb48f4fdb8f904d31f3752503"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4a36a987d33846ce873195d6b53fbcdc?KeyID=8f2f71ed&Signature=TJHSDvK%252B25lwWqrTpCHw%2FxFajvBCLFy424jp%252BNekwCwclJp7a7xDVthyjFFK0GWry3%2F82FeruAcw0qBP67nKDQ%253D%253D", 
      "title": "contract_second_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:36.562256+03:00", 
      "dateModified": "2017-03-29T15:47:36.562283+03:00", 
      "id": "0c9d642e2a29402591bd60c0d9de16f3"
    }
  ]
}

