PATCH /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/contracts/ada81c2080f143a387863faae3db1f81?acc_token=ccf4d45ff9524ec9ae87f38c43d7b0a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2017-11-30T16:56:29.280738+02:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/5bd3f7a02ff44727b232621207f1b851?KeyID=8473a74a&Signature=JQHt0PL4w47AD3VLzHc10HkPeKF1%252BHLSabNSU66N7xOOgzeZ5ABgvszpMW%252Bf1dAvGCTqIVBaD2EYUV1iUuYZAQ%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:28.913379+02:00", 
        "dateModified": "2017-11-30T16:56:28.913410+02:00", 
        "id": "1702fe06543e4c10b6f0bcb0aa694e8c"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4d1df678191e499cbb764244f4469b22?KeyID=8473a74a&Signature=jAmAX7MaWviKJdsUEYM2RR8oXbt8vNobcDP6zqadHWj%252BoQKkUnjVwDry6HmSExDU7DJCqVN9ReLo4mMzNmibBQ%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:29.118456+02:00", 
        "dateModified": "2017-11-30T16:56:29.118484+02:00", 
        "id": "5c42650d4e074aae85732d8655eec1b7"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "6abd12c929084367ac08d9d9138ccab4", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-11-30T16:56:17.205813+02:00", 
      "endDate": "2018-11-30T16:56:17.205813+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-11-30T16:56:29.280738+02:00", 
    "date": "2017-11-30T16:56:29.382454+02:00", 
    "awardID": "add0cbb7aa114e7cb6f5e127071f8b53", 
    "id": "ada81c2080f143a387863faae3db1f81", 
    "contractID": "UA-PS-2017-11-30-000001-1"
  }
}

