GET /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-03-29-000001", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/a3fe480fc194429db59b3517ac2becff", 
    "enquiryPeriod": {
      "startDate": "2017-03-22T15:47:26.505267+02:00", 
      "endDate": "2017-03-29T15:47:26.505267+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-03-29T16:31:26.505267+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2017-03-29T15:47:34.865633+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "c6c6259846504cfbb4e38d9c5d543958", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "a3fe480fc194429db59b3517ac2becff", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c683de25eb294b5fa8cc8294ec9fe908?KeyID=8f2f71ed&Signature=b1At6NDAC3JTU6fDd9uTHG1sI%2FzioJcoVHbxqTzZAELtHr3FwOjQ9yMpVBRf%2FFrizC84qhF2xqlfr51ifFqoBg%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.401607+03:00", 
        "documentType": "technicalSpecifications", 
        "dateModified": "2017-03-29T15:47:34.401638+03:00", 
        "id": "2a0f652e19154a218c608f42a5c448e0"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25ff4fb78e0247c1ba9d86dfe133e8f2?KeyID=8f2f71ed&Signature=zvXLkJyiCc6psFjTxZ0D%2FQLdBfZcvHph5gX1092UY1rharY6SgOr379PFead3dzGytmiIC%252BdtyIReRug7BUZDw%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.472264+03:00", 
        "dateModified": "2017-03-29T15:47:34.472306+03:00", 
        "id": "18fb51d188ce405e875dfb37f1baf161"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a70797d6dbde47c897ae6a0dfe2af58e?KeyID=8f2f71ed&Signature=PSvGpJaKdUzNhQ5doYcyhvffRxRvLNo2w3YI5U9fSNzR5%2FOp2TZCDDj6Ebre6Wfc7zgLutisTUqCzBy7X4fBBg%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.472264+03:00", 
        "dateModified": "2017-03-29T15:47:34.531556+03:00", 
        "id": "18fb51d188ce405e875dfb37f1baf161"
      }, 
      {
        "index": 1, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "First illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7775106db07c466c9750e75e3a1b1d6b?KeyID=8f2f71ed&Signature=ILUThMRo0qZCi8tZWpKJU3823B3hGbztKBm7Xm25aJXdqBbYELIZDig2uPsixRPRueqmQBR7imEfx3lJrAv1CQ%253D%253D", 
        "title": "first_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.591738+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-03-29T15:47:34.591779+03:00", 
        "id": "8c81536a6660418483282224f74adfec"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Second illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4729e391cb144b07991bac85f9c818c5?KeyID=8f2f71ed&Signature=jFB8Hk2RJDmeK6F%2Flwn7VOnF4YACkiKim38m19aiGbnpwg0HB%2FOHxh0jBicpQblc7FuPXhMJpU%2FEDgElJoNBDw%253D%253D", 
        "title": "second_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.656709+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-03-29T15:47:34.656745+03:00", 
        "id": "6e61fb44da8145ed89b3762be3ef21f6"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Third illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7085d82dbfc4481fadf1ea3398627992?KeyID=8f2f71ed&Signature=90AdYhugdyIJ8Na8%2FJBokHs%252BOUpjxiUfBhXvINxrzqd0rvQOwHap64cd1qvN4uqEUZipHq%2FHxfvi%252BHWHGRwqDA%253D%253D", 
        "title": "third_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.713380+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-03-29T15:47:34.713406+03:00", 
        "id": "72ae2b129ab4497ea20f48fea7d518be"
      }, 
      {
        "title": "Familiarization with bank asset", 
        "format": "offline/on-site-examination", 
        "accessDetails": "Familiar with asset: days, time, address", 
        "documentOf": "tender", 
        "datePublished": "2017-03-29T15:47:34.786322+03:00", 
        "documentType": "x_dgfAssetFamiliarization", 
        "dateModified": "2017-03-29T15:47:34.786347+03:00", 
        "id": "dec6a7e47b7f46928bfaf397365e0d5e"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-03-29T15:47:35.557500+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2017-03-22T15:47:26.505267+02:00", 
      "endDate": "2017-03-29T15:47:26.505267+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2017-03-29T15:47:26.505267+03:00", 
      "shouldStartAfter": "2017-03-30T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-03-29T15:47:33.994721+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "d3a6b745e6ec4a3fabba32445167d78c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

