POST /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/awards/add0cbb7aa114e7cb6f5e127071f8b53/documents?acc_token=73842c515600468a8829fea44817fce1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 385
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/326d29c8df4744149f6082d061e6492e?KeyID=8473a74a&Signature=4cNJZ9v3X0JCIiaW9cFX2nbH10INN6%2B%2FLVLrM4p%2FwQQo%2FBU2JD1ryXuz6r6SxP7hcfQpgAtoL%2F2WB5QRENZvCA%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/awards/add0cbb7aa114e7cb6f5e127071f8b53/documents/de5b4f4f5aa04ef6a16606d1152b061a

{
  "data": {
    "dateModified": "2017-11-30T16:56:28.083997+02:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/326d29c8df4744149f6082d061e6492e?KeyID=8473a74a&Signature=W07o9qqLEOV3dvjZZVzBFeolqx4QEUoFCZPnHeu4xyBsP7NJma%252BZINjCbfVSmXeRHYiAnDikplownjV%2FJE%252B6BQ%253D%253D", 
    "author": "bid_owner", 
    "documentOf": "tender", 
    "datePublished": "2017-11-30T16:56:28.083969+02:00", 
    "documentType": "auctionProtocol", 
    "title": "SignedAuctionProtocol.pdf", 
    "id": "de5b4f4f5aa04ef6a16606d1152b061a"
  }
}

