POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2029
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "tenderAttempts": 1, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "mode": "test", 
    "title_ru": "футляры к государственным наградам", 
    "auctionPeriod": {
      "startDate": "2017-12-14T16:56:17.205813"
    }, 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "aff7d0febd8847b78f31662488efd20b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "title_en": "Cases with state awards", 
    "dgfID": "219560"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/057ecdd1ad8f45ea8151e731ac2b30f3

{
  "access": {
    "token": "52d7fbc91420401d908289b3cbfe71e9"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-11-30-000002", 
    "enquiryPeriod": {
      "startDate": "2017-11-30T16:56:25.801167+02:00", 
      "endDate": "2017-12-14T16:55:24.860531+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-12-14T16:55:24.860531+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "057ecdd1ad8f45ea8151e731ac2b30f3", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-11-30T16:56:25.805777+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-11-30T16:56:25.801167+02:00", 
      "endDate": "2017-12-14T16:55:24.860531+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-12-15T00:00:00+02:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-11-30T16:56:25.801167+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "aff7d0febd8847b78f31662488efd20b", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "awardCriteria": "highestCost"
  }
}

