PUT /api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents/a4a5eb45f2c1457d8b1daa1256842b38?acc_token=55adce4ad40548ec879f68439cae2a70 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 340
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6f5c759f19264080bf7601a9499f0244?KeyID=8e787cc1&Signature=FcppEwGtSMHHZ7%2FLf7FDnMNzrDaLOE3AoeG4P8FPZ3GMC6KgTcoGhlR%2BZZZKv3Gk4IeITQuu%2FTVZEvEqyTw0BQ%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/6f5c759f19264080bf7601a9499f0244?KeyID=8e787cc1&Signature=9V%2FRnSXWH6L5JWR2nXFyEIS2QfcGVCJnZvvH%252B1hMiLVi6ZdUmAQrXELTocMSgGy1PcCa9uK7N5KBqXQtvo37Cg%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:32.670097+03:00", 
    "dateModified": "2017-03-29T15:47:32.732183+03:00", 
    "id": "a4a5eb45f2c1457d8b1daa1256842b38"
  }
}

