POST /api/2.3/auctions/73e1598288054eb98e8153ee9e69bb28/documents?acc_token=6c03609dd6844e42bc1318fddf20c937 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b0a0c1a4b083475caaa4c8fb08d18781?KeyID=c822be4a&Signature=eUjEvPipgCDUg2CRW0uqyy%2Br5C7MNpbTp26C83J4cy7H84gzepDYr%2BfNWkPzjpTqZfg%2BIfTNVj86hY07Z9mcBA%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/73e1598288054eb98e8153ee9e69bb28/documents/55dc8e33c47948eab4e7b327bede3959

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b0a0c1a4b083475caaa4c8fb08d18781?KeyID=c822be4a&Signature=xnYvodjAvZu8pjdlyQ4kdlC62x%252BEi2JnnuWKvRdNbne9KWdXVWSlqM%252BeGrGuJ4%252BS2e9qmZRCg9vHJvc1iz%252BMAA%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-11-30T16:56:24.174808+02:00", 
    "dateModified": "2017-11-30T16:56:24.174838+02:00", 
    "id": "55dc8e33c47948eab4e7b327bede3959"
  }
}

