GET /api/2.3/auctions/73e1598288054eb98e8153ee9e69bb28/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1b63ae48aa3e4caf99aac3455888c7d6?KeyID=c822be4a&Signature=Cqo%2Fl%2FHX9fy29aZ4TPnu9LB6ZtHdt6tquLKAJIGPLchoAf4OTMDnRAqLTeQK8rW9jgzFQ6I9HGfJtUP8i3gKDA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-11-30T16:56:24.108881+02:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-11-30T16:56:24.108911+02:00", 
      "id": "74e4e4b7624d420b8448a6220e0a86cf"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b0a0c1a4b083475caaa4c8fb08d18781?KeyID=c822be4a&Signature=xnYvodjAvZu8pjdlyQ4kdlC62x%252BEi2JnnuWKvRdNbne9KWdXVWSlqM%252BeGrGuJ4%252BS2e9qmZRCg9vHJvc1iz%252BMAA%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-11-30T16:56:24.174808+02:00", 
      "dateModified": "2017-11-30T16:56:24.174838+02:00", 
      "id": "55dc8e33c47948eab4e7b327bede3959"
    }
  ]
}

