POST /api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents?acc_token=55adce4ad40548ec879f68439cae2a70 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 127
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://virtial-data-room.com/id_of_room", 
    "title": "VDR for auction lot", 
    "documentType": "virtualDataRoom"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents/ec9229c09053434a8035d1cc92b4d3eb

{
  "data": {
    "title": "VDR for auction lot", 
    "url": "http://virtial-data-room.com/id_of_room", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:32.790398+03:00", 
    "documentType": "virtualDataRoom", 
    "dateModified": "2017-03-29T15:47:32.790425+03:00", 
    "id": "ec9229c09053434a8035d1cc92b4d3eb"
  }
}

