GET /api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59e07eacaac5460ebb1e9e2fa16c3776?KeyID=8e787cc1&Signature=UliwRYrzr2iL4DXd1GJE%2FVvXNRJpQXshXcWcB52gQkqEfqB51VC4e%2Frg20%252B5eckaOvVEcgjJ4wfr877TuCC%2FDQ%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:32.613197+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-03-29T15:47:32.613225+03:00", 
      "id": "7b58a8734f3841868d167fa0f34324ef"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bb5bc26b5b224ec1b0bb166798f840ce?KeyID=8e787cc1&Signature=Fi%2FmhACH1ZjyaLMyySG8r8NPaJ%252BFqkQ8VBj7nm8brELNrz6jM0LAo7b307ANpV%252B5Tlj5H5o8pH2xazNP2krfBg%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-03-29T15:47:32.670097+03:00", 
      "dateModified": "2017-03-29T15:47:32.670134+03:00", 
      "id": "a4a5eb45f2c1457d8b1daa1256842b38"
    }
  ]
}

