GET /api/2.3/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.3/auctions?offset=2017-11-30T16%3A56%3A25.621767%2B02%3A00", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.3/auctions?offset=2017-11-30T16%3A56%3A25.621767%2B02%3A00", 
    "offset": "2017-11-30T16:56:25.621767+02:00"
  }, 
  "data": [
    {
      "id": "301d66e275cb4861ba502c1eaafa88ae", 
      "dateModified": "2017-11-30T16:56:25.621767+02:00"
    }
  ]
}

