PATCH /api/2.3/auctions/aad622eb435a443e8a7afd5432c5d4e6?acc_token=8f2c28a574a647ab8f3dfaeadbbbadb2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2076
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "tenderAttempts": 1, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "dgfID": "219560", 
    "auctionPeriod": {
      "startDate": "2017-12-04"
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "contractPeriod": {
          "startDate": "2017-11-22T15:29:31.486546", 
          "endDate": "2017-11-25T15:29:31.486546"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.001
      }
    ], 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


403 Forbidden
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": "Auction can be edited only during the rectification period: from (2017-11-06T15:29:31.491067+02:00) to (2017-11-20T15:28:31.491067+02:00).",
      "location": "body", 
      "name": "data"
    }
  ]
}

