PATCH /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/cancellations/3fd26d96a4454abf9a875bef110dba4e/documents/6aebbc98305a4847830bdc40863a4d6b?acc_token=ccf4d45ff9524ec9ae87f38c43d7b0a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/02dd9977d20e4b409d307bc67ee6ca36?KeyID=8473a74a&Signature=5WtHn%252BXf4U2eKnBY5mwdZNifHaf%2FMoApsRroJSOzQBI%252BdJ5ZwCkP%252BTZmjkZ%2FDOh1M4U5JY7u1MJE8%252Bp7YQOSBw%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-11-30T16:56:29.945693+02:00", 
    "dateModified": "2017-11-30T16:56:29.945720+02:00", 
    "id": "6aebbc98305a4847830bdc40863a4d6b"
  }
}

