PATCH /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-04-13T15:47:44.279764+03:00"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-03-29-000001", 
    "enquiryPeriod": {
      "startDate": "2017-03-29T15:47:33.994721+03:00", 
      "endDate": "2017-04-11T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2017-04-11T23:59:50+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "a3fe480fc194429db59b3517ac2becff", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-03-29T15:47:33.997773+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-03-29T15:47:33.994721+03:00", 
      "endDate": "2017-04-11T23:59:50+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-04-12T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-03-29T15:47:33.994721+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "d3a6b745e6ec4a3fabba32445167d78c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

