PATCH /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/cancellations/a167f5e9c4df43cf802e8ebebe1380c7/documents/2a5e5d1b56604d5fba0c342cb8eda4ee?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/29adbb9dc3f648a6aa4839f553b63cd6?KeyID=8f2f71ed&Signature=yNCxpNRyKhm0gJl9Pv26P5tPHMdippd5vmXIig3FTdAwdwP8TTjNkobkrgSMrW8i7%2FelyneDx%252BnzPJqAO2EVBQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:37.082686+03:00", 
    "dateModified": "2017-03-29T15:47:37.082713+03:00", 
    "id": "2a5e5d1b56604d5fba0c342cb8eda4ee"
  }
}

