POST /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/cancellations?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/cancellations/a167f5e9c4df43cf802e8ebebe1380c7

{
  "data": {
    "date": "2017-03-29T15:47:36.955094+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "a167f5e9c4df43cf802e8ebebe1380c7"
  }
}

