POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2037
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2017-09-02T15:56:30.045984"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "dgfID": "219560", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "contractPeriod": {
          "startDate": "2017-08-30T15:56:30.043635", 
          "endDate": "2017-09-02T15:56:30.043635"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.001
      }
    ], 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


422 Unprocessable Entity
Content-Type: application/json; charset=UTF-8

{
  "status": "error", 
  "errors": [
    {
      "description": [
        "tenderPeriod should be greater than 6 days"
      ], 
      "location": "body", 
      "name": "tenderPeriod"
    }
  ]
}

