POST /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/documents?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25ff4fb78e0247c1ba9d86dfe133e8f2?KeyID=8f2f71ed&Signature=RsoR%2BvEI1uiT2wE%2FxHEena5fSTtCIcpL7I5XSdzXwlZcZBwOlzXwyHWjxy7wq%2BY3sVGWFxKq8sE4V469r5KfCg%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/documents/18fb51d188ce405e875dfb37f1baf161

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/25ff4fb78e0247c1ba9d86dfe133e8f2?KeyID=8f2f71ed&Signature=zvXLkJyiCc6psFjTxZ0D%2FQLdBfZcvHph5gX1092UY1rharY6SgOr379PFead3dzGytmiIC%252BdtyIReRug7BUZDw%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:34.472264+03:00", 
    "dateModified": "2017-03-29T15:47:34.472306+03:00", 
    "id": "18fb51d188ce405e875dfb37f1baf161"
  }
}

