POST /api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/documents?acc_token=149ad798bd474ec4af76cd8e6756b307 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 432
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7085d82dbfc4481fadf1ea3398627992?KeyID=8f2f71ed&Signature=z2GeUFtWFsNOaIWydSv%2BVzw0dmtZBNDct1Th0%2BJAK1u7OYmzXR8Scjg%2BAiqfhOfVxKGYtUg624fvsjbwPki8Aw%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a3fe480fc194429db59b3517ac2becff/documents/72ae2b129ab4497ea20f48fea7d518be

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7085d82dbfc4481fadf1ea3398627992?KeyID=8f2f71ed&Signature=90AdYhugdyIJ8Na8%2FJBokHs%252BOUpjxiUfBhXvINxrzqd0rvQOwHap64cd1qvN4uqEUZipHq%2FHxfvi%252BHWHGRwqDA%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:34.713380+03:00", 
    "documentType": "illustration", 
    "dateModified": "2017-03-29T15:47:34.713406+03:00", 
    "id": "72ae2b129ab4497ea20f48fea7d518be"
  }
}

