POST /api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents?acc_token=55adce4ad40548ec879f68439cae2a70 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 410
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59e07eacaac5460ebb1e9e2fa16c3776?KeyID=8e787cc1&Signature=9XJisfG0euF5y41iUZBzT5fYRzgBmaMrlXoGOGyl9BObmFw10KLPwEPIClVUJnnZZk7OssKaSzIOJB6ijnBTCw%3D%3D", 
    "format": "application/pdf", 
    "documentType": "technicalSpecifications"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/a66af4ecf50e4a9ba3c0a287b0c13de1/documents/7b58a8734f3841868d167fa0f34324ef

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59e07eacaac5460ebb1e9e2fa16c3776?KeyID=8e787cc1&Signature=UliwRYrzr2iL4DXd1GJE%2FVvXNRJpQXshXcWcB52gQkqEfqB51VC4e%2Frg20%252B5eckaOvVEcgjJ4wfr877TuCC%2FDQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-03-29T15:47:32.613197+03:00", 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-03-29T15:47:32.613225+03:00", 
    "id": "7b58a8734f3841868d167fa0f34324ef"
  }
}

