PATCH /api/2.3/auctions/301d66e275cb4861ba502c1eaafa88ae/awards/add0cbb7aa114e7cb6f5e127071f8b53?acc_token=ccf4d45ff9524ec9ae87f38c43d7b0a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "pending.payment"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending.payment", 
    "paymentPeriod": {
      "startDate": "2017-11-30T16:56:27.695166+02:00", 
      "endDate": "2017-11-30T17:16:29.509749+02:00"
    }, 
    "documents": [
      {
        "dateModified": "2017-11-30T16:56:28.083997+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/326d29c8df4744149f6082d061e6492e?KeyID=8473a74a&Signature=W07o9qqLEOV3dvjZZVzBFeolqx4QEUoFCZPnHeu4xyBsP7NJma%252BZINjCbfVSmXeRHYiAnDikplownjV%2FJE%252B6BQ%253D%253D", 
        "author": "bid_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:28.083969+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "de5b4f4f5aa04ef6a16606d1152b061a"
      }, 
      {
        "dateModified": "2017-11-30T16:56:28.217417+02:00", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/79f7d75e9ff34c1d94289241ebd04a46?KeyID=8473a74a&Signature=ZZf5dIDTAFetGGoNyGHK0TaTX%2FMo%2FTcKq%2FTatSSpuIZleTjJFvbciSiMq9MNq3mZGWRdK%2FYKfT0lkoOKYooXDA%253D%253D", 
        "author": "auction_owner", 
        "documentOf": "tender", 
        "datePublished": "2017-11-30T16:56:28.217384+02:00", 
        "documentType": "auctionProtocol", 
        "title": "SignedAuctionProtocol.pdf", 
        "id": "edc7c486de494ac3bdcc0b456d006e4a"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2017-11-30T16:56:27.695166+02:00", 
      "endDate": "2017-11-30T16:56:28.375177+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2017-11-30T16:56:27.695166+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2017-11-30T16:56:27.695166+02:00", 
      "endDate": "2017-11-30T17:16:29.509749+02:00"
    }, 
    "bid_id": "0d76a3f619044106b9bcdc0e57e93dad", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-11-30T16:56:28.382166+02:00", 
    "id": "add0cbb7aa114e7cb6f5e127071f8b53"
  }
}

